# Generated by Django 4.2.7 on 2023-11-22 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="faq",
            table="faq",
        ),
    ]
