# Generated by Django 4.2.7 on 2023-11-22 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_alter_faq_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="faq",
            table=None,
        ),
    ]
